---
version: '3'
networks:
  twitter:
    driver: bridge
volumes:
  hdfs:
  database:
services:
  hdfs:
    networks:
      - twitter
    volumes:
      - hdfs:/tmp/hdfs
    restart: on-failure
    ports:
      - 9000:9000
      - 9864:9864
      - 9870:9870
    build:
      context: ./sources/hdfs
  zookeeper:
    networks:
      - twitter
    image: confluentinc/cp-zookeeper:latest
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    networks:
      - twitter
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    restart: on-failure
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://192.168.1.22:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  mongo:
    networks:
      - twitter
    volumes: 
      - database:/data/db
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    networks:
      - twitter
    image: mongo-express
    depends_on:
      - mongo
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
  producer:
    networks:
      - twitter    
    depends_on:
      - kafka
    restart: on-failure
    build:
      context: ./sources/producer
  jupyter:
    networks:
      - twitter
    volumes: 
      - ./:/home/jovyan
    image: jupyter/pyspark-notebook:latest
    depends_on:
      - hdfs
    restart: on-failure
    ports:
      - 8888:8888
    environment:
      HADOOP_USER_NAME: root
